baseURL: 'https://y7ut.github.io'
title: 'è¿˜æ˜¯å¶å°”æƒ³è¦ä¼Ÿå¤§'
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: 'Wooo...'
homepage: 'https://y7ut.github.io'
defaultContentLanguage: 'en'
paginate: 10
menu:
  main:
    - name: Blog
      url: /blog
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: Archive
      url: /archives
      weight: 3
params:
  brand: HOME
  avatarURL: /images/yichu.jpg
  author: æ˜“åˆ
  authorDescription: 'RUN RUN RUN'
  info: 'ğŸè¿˜æ˜¯å¶å°”æƒ³è¦ä¼Ÿå¤§'
  favicon: /images/robot.ico
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
  darkModeTheme: data-dark-mode
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/y7ut'
languages:
  en:
    languageName: EN
  zh:
    languageName: ä¸­
    author: æ˜“åˆ
    authorDescription: 'RUN RUN RUN'
    info: 'ğŸè¿˜æ˜¯å¶å°”æƒ³è¦ä¼Ÿå¤§'
    menu:
      main:
        - name: æ–‡ç« 
          url: /blog
          weight: 1
        - name: åˆ†ç±»
          url: /tags
          weight: 2
        - name: å†å²æ–‡ç« 
          url: /archives
          weight: 3
taxonomies:
  series: series
  tag: tags
